# -*- coding: utf-8 -*-
"""gtfs_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EY1HELwaFBiCY46BbAQNuTIBM_PQFhdp
"""


# !pip install gtfs_functions
# !pip install keplergl
# !jupyter nbextension install --py --sys-prefix keplergl # can be skipped for notebook 5.3 and above
# !jupyter nbextension enable --py --sys-prefix keplergl # can be skipped for notebook 5.3 and above

import geopandas as gpd
import pandas as pd

from gtfs_functions_sample import Feed

gtfs_path = "https://feeds.mta.maryland.gov/gtfs/local-bus"
feed = Feed(gtfs_path, time_windows=[0, 6, 10, 12, 16, 19, 24])
routes = feed.routes
routes.head(2)

shapes = feed.shapes
shapes.head(2)

time_windows = [0, 6, 9, 15.5, 19, 22, 24]

feed = Feed(gtfs_path, time_windows=time_windows)
stop_freq = feed.stops_freq
stop_freq.head(2)

line_freq = feed.lines_freq
line_freq.head()

segments_gdf = feed.segments
segments_gdf.head(2)

# Cutoffs to make get hourly values
speeds = feed.avg_speeds
speeds.head(1)

segments_freq = feed.segments_freq
segments_freq.head(2)

"""## Map your work"""

stop_freq

stop_freq.direction_id.unique()

# Stops
from gtfs_functions.gtfs_plots import map_gdf

condition_dir = stop_freq.direction_id == 0
condition_window = stop_freq.window == "6:00-9:00"

gdf = stop_freq.loc[(condition_dir & condition_window), :].reset_index()

map_gdf(
    gdf=gdf,
    variable="ntrips",
    colors=["#d13870", "#e895b3", "#55d992", "#3ab071", "#0e8955", "#066a40"],
    tooltip_var=["min_per_trip"],
    tooltip_labels=["Frequency: "],
    breaks=[10, 20, 30, 40, 120, 200],
)

# Line frequencies
from gtfs_functions.gtfs_plots import map_gdf

condition_dir = line_freq.direction_id == 0
condition_window = line_freq.window == "6:00-9:00"

gdf = line_freq.loc[(condition_dir & condition_window), :].reset_index()

map_gdf(
    gdf=gdf,
    variable="ntrips",
    colors=["#d13870", "#e895b3", "#55d992", "#3ab071", "#0e8955", "#066a40"],
    tooltip_var=["route_name"],
    tooltip_labels=["Route: "],
    breaks=[5, 10, 20, 50],
)

# Line frequencies
from gtfs_functions.gtfs_plots import map_gdf

condition_dir = line_freq.direction_id == 1
condition_window = line_freq.window == "6:00-9:00"

gdf = line_freq.loc[(condition_dir & condition_window), :].reset_index()

map_gdf(
    gdf=gdf,
    variable="ntrips",
    colors=["#d13870", "#e895b3", "#55d992", "#3ab071", "#0e8955", "#066a40"],
    tooltip_var=["route_name"],
    tooltip_labels=["Route: "],
    breaks=[
        1,
        5,
        10,
        20,
    ],
)


# # Speeds
# import keplergl as kp
# m = kp.KeplerGl(data=dict(data=speeds, name='Speed Lines'), height=400)
# m
